Expose the VTE flags
Aetf/libtsm pull request #28
Opened 2022-08-07 11:41 UTC by aheck

This allows the client of the library to supervise the current state
of the terminal and can be useful e.g. for writing your own keyboard
handler.

2022-09-18 05:26 UTC, Aetf requested changes
New function needs to be added to https://github.com/Aetf/libtsm/blob/develop/src/tsm/libtsm.sym#L126

2022-09-19 20:16 UTC, aheck commented
I added the new function to libtsm.sym and resolved a merge conflict that was caused by the merge of decrqm-reset-bug.

2022-09-20 07:55 UTC, Aetf commented
Awesome, thanks!

2022-09-20 07:55 UTC, Aetf approved these changes

2022-09-20 07:55 UTC, merged