Add mouse tracking
Aetf/libtsm pull request #29
Opened 2022-08-07 13:10 UTC by aheck

This patch implements the legacy X10 mode and the newer SGR and SGR Pixel modes. It omits the EXT and URXVT modes because their use is discouraged anyway (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking). With the first one the encoding is ambigious and the second one is no improvement over SGR mode. Not implementing them keeps the complexity down and if people actually use them (which they shouldn't) we could still add them in the future.

X10 can only encode a limited number of rows and cols (224) which can be a problem with modern ultra-wide displays. But AFAIK people used it in the past and it is good to have it for compatibility. SGR is the new encoding that fixes X10 and SGR Pixel mode was introduced by xterm in 2020 and allows to track pixels instead of rows and cols and might see more use in the future.

In addition to the unit tests (which I derived from values gathered from xterm) I tested it in midnight commander and clicking as well as scrolling with the mouse wheel worked as expected.

2022-09-18 05:24 UTC, Aetf requested changes
Overall looks good other than a few nitpicks. Also, please add new functions to [`libtsm.sym`](https://github.com/Aetf/libtsm/blob/develop/src/tsm/libtsm.sym#L126).

2022-09-18 05:24 UTC, Aetf commented on src/tsm/tsm-vte.c
> +
Redundant?

2022-09-18 05:24 UTC, Aetf commented on test/test_vte.c
> +
Whitespace

2022-09-18 05:24 UTC, Aetf commented on src/tsm/libtsm.h
> +#define TSM_VTE_MOUSE_MODE_PIXEL 1016
Please add some comments about their usage later in state machine handling. It was a bit unclear to me at first why these particular values were chosen until I realized they are part of the control sequence.

2022-09-18 05:24 UTC, Aetf commented on src/tsm/libtsm.h
> +bool tsm_vte_handle_mouse(struct tsm_vte *vte, unsigned int cell_x,
Some documentation here about how this is supposed to be used would be useful. We already don't have API docs, so please at least provide some useful info in the form of comments :)

2022-09-19 22:41 UTC, aheck commented
I think I fixed everything.

2022-09-20 07:58 UTC, Aetf approved these changes

2022-09-20 08:15 UTC, Aetf approved these changes

2022-09-20 08:19 UTC, merged